kind: Pod
apiVersion: v1
metadata:
  name: test-pod-cephfs02
  labels:
    test-rbd: "true"
spec:
  containers:
  - name: test-pod2
    image: harbor.ngcp.com/busybox:latest
    imagePullPolicy: IfNotPresent
    command:
    - "/bin/sh"
    args:
    - "-c"
    - "trap exit TERM; while true; do sleep 1; done"
    volumeMounts:
    - name: data
      mountPath: "/mnt"
  volumes:
  - name: data
    persistentVolumeClaim:
      claimName: cephfs-claim2
